version: "3.9"

services:
  app:
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./src:/app/src
      - ./templates:/app/templates
      - ./static:/app/static
    environment:
      - DATABASE_URL=postgresql://postgres@db:5432/battleship_revamp
      - SQLALCHEMY_ECHO=true
