services:
  db_test:
    image: postgres:16
    environment:
      POSTGRES_DB: battleship_revamp_test
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    ports:
      - "6543:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d battleship_revamp_test"]
      interval: 1s
      timeout: 3s
      retries: 30
    secrets:
      - postgres_password
secrets:
  postgres_password:
    file: ./secrets/postgres_password.txt
